### ISSUE TITLE
Customization Issues -- Turn off trackers

### ISSUE THREAD

**Issue by grantopher** [nwinter/telepath-logger#6]
Is there a way to turn off some of the features on your application? I'm not wanting to use the webcam capture. I tried looking for some sort of settings object but I didn't see anything.

**Comment by nwinter** [comment]
Yup–in fact, I have the webcam one turned off right now, too. You should just be able to comment out any trackers you don't want [in TPTracker.m](https://github.com/nwinter/telepath-logger/blob/master/Telepath/TPTracker.m#L98-L106).

**Comment by grantopher** [comment]
Thanks for the quick response! I'm loving your application. Should it be auto starting sessions when I open up the application? The time tracker doesn't start up and There aren't any buttons or context menus that would start the timer (that I can see).

**Comment by nwinter** [comment]
The time tracker only really works if you are sending distributed notifications to start/stop it from some other app, like I do in a Python program that parses my Emacs buffer for work timestamps and sends a distributed notification, like this:

``` python
import Foundation
# ... do stuff to figure out what the work times are ...
user_info = {"sessionHours": total_session, "dayHours": total_today, "weekHours": total_this_week}
nc = Foundation.NSDistributedNotificationCenter.defaultCenter()
nc.postNotificationName_object_userInfo_deliverImmediately_('net.nickwinter.Telepath.WorkChanged', None, user_info, True)
```

Sorry, internal use tool! You could probably add a start/stop button to the UI without much trouble; I like the editing-of-timestamp-text-file approach because I can easily retroactively fix start/stop times, send data to my webserver, etc.

**Comment by grantopher** [comment]
Ah, I see. Well it was worth a shot. Thanks for the feedback. I'll see if I can't add a start/stop button when I get get some time. Coming up on a major deployment date.
