### ISSUE TITLE
How to collect time/date of when certain patterns are typed?

### ISSUE THREAD

**Issue by josephdburdick** [nwinter/telepath-logger#7]
Hi, I want to use this to measure how many times I hit command + S during a work day. Is there a way to detect this pattern and log the time/date somewhere? Thanks!

**Comment by nwinter** [comment]
You could either add some handling to [onKeyEvent: up:](https://github.com/nwinter/telepath-logger/blob/master/Telepath/TPTrackerKeyboard.m#L114-L136) in TPTrackerKeyboard.m, possibly looking at how `checkReallyBadStuff` is implemented, or you could use Telepath as-is and write a one-off parser to go through the logs it generates to detect that pattern (or any other arbitrary pattern you are interested in). If you want it to show up in the dashboard, you'd take the first route so that you could count these occurrences live.

Hope this answers your question!
